# Generated by Django 4.2.9 on 2024-07-03 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_user_avatar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["-updated", "created"]},
        ),
    ]
