# Generated by Django 4.2.9 on 2024-07-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_message_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message", options={"ordering": ["updated", "created"]},
        ),
    ]
